name: CI-roundoff

on: push

jobs:
  pytest:
    name: ${{ matrix.name }}
    runs-on: "${{ matrix.os }}"

    env:
      DEVITO_ARCH: "${{ matrix.arch }}"
      DEVITO_LANGUAGE: ${{ matrix.language }}
      DEVITO_BACKEND: "core"
      OMP_NUM_THREADS: 2
      PYTHON_VERSION: "${{ matrix.python-version }}"
      TESTS: "tests/"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

      matrix:
        name: [
           pytest-ubuntu-py36-gcc49-omp,
           pytest-ubuntu-py37-gcc5-omp,
           pytest-ubuntu-py38-gcc6-omp,
           pytest-ubuntu-py36-gcc7-omp,
           pytest-ubuntu-py37-gcc7-noomp,
           pytest-ubuntu-py37-gcc8-omp,
           pytest-ubuntu-py38-gcc9-omp,
           pytest-osx-py37-clang-omp,
           pytest-docker-py36-gcc-omp
        ]
        include:
        - name: pytest-ubuntu-py36-gcc49-omp
          python-version: 3.6
          os: ubuntu-16.04
          arch: "gcc-4.9"
          language: "openmp"

        - name: pytest-ubuntu-py37-gcc5-omp
          python-version: 3.7
          os: ubuntu-18.04
          arch: "gcc-5"
          language: "openmp"

        - name: pytest-ubuntu-py38-gcc6-omp
          python-version: 3.8
          os: ubuntu-18.04
          arch: "gcc-6"
          language: "openmp"

        - name: pytest-ubuntu-py36-gcc7-omp
          python-version: 3.6
          os: ubuntu-18.04
          arch: "gcc-7"
          language: "openmp"

        - name: pytest-ubuntu-py37-gcc7-noomp
          python-version: 3.7
          os: ubuntu-18.04
          arch: "gcc-7"
          language: "C"

        - name: pytest-ubuntu-py37-gcc8-omp
          python-version: 3.7
          os: ubuntu-18.04
          arch: "gcc-8"
          language: "openmp"

        - name: pytest-ubuntu-py38-gcc9-omp
          python-version: 3.8
          os: ubuntu-18.04
          arch: "gcc-9"
          language: "openmp"

        - name: pytest-osx-py37-clang-omp
          python-version: 3.7
          os: macos-latest
          arch: "osx"
          language: "C"

        - name: pytest-docker-py36-gcc-omp
          python-version: 3.6
          os: ubuntu-18.04
          arch: "gcc"
          language: "openmp"

    steps:
    - name: Checkout devito
      uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      if: matrix.name != 'pytest-docker-py36-gcc-omp'
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build docker image
      if: matrix.name == 'pytest-docker-py36-gcc-omp'
      run: |
          docker build . --file docker/Dockerfile --tag devito_img
          echo "::set-env name=RUN_CMD::docker run --rm --name testrun devito_img"

    - name: Install GCC ${{ matrix.arch }}
      if: runner.os == 'linux'
      run : |
        sudo apt-get install -y ${{ matrix.arch }}

    - name: Reduce number of tests for OSX
      if: runner.os == 'macOS'
      run : |
        echo "::set-env name=TESTS::tests/test_operator.py"

    - name: Install dependencies
      if: matrix.name != 'pytest-docker-py36-gcc-omp'
      run: |
        pip install --upgrade pip
        pip install -e .

    - name: Test with pytest
      run: |
        $RUN_CMD pytest tests/test_roundoff.py
